version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: labdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  inputapp:
    build: ./inputapp
    container_name: inputapp
    ports:
      - "5001:5000"
    environment:
      TZ: Asia/Jakarta
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: labdb
    depends_on:
      - mariadb

  displayapp:
    build: ./displayapp
    container_name: displayapp
    ports:
      - "5002:5000"
    environment:
      TZ: Asia/Jakarta
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: labdb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
