apiVersion: apps/v1
kind: Deployment
metadata:
  name: inputapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inputapp
  template:
    metadata:
      labels:
        app: inputapp
    spec:
      containers:
        - name: inputapp
          image: khalilghibran/inputapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mariadb-0.mariadb"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"
            - name: DB_NAME
              value: "labdb"
